/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotesUXLawsRouteImport } from './routes/notes.21-ux-laws'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as ExperimentsRightProblemRouteImport } from './routes/experiments.right-problem'
import { Route as ExperimentsMagazineWebsitesRouteImport } from './routes/experiments.magazine-websites'
import { Route as ExperimentsBokksuIndiaRouteImport } from './routes/experiments.bokksu-india'
import { Route as CaseStudiesReclaimRouteImport } from './routes/case-studies.reclaim'
import { Route as CaseStudiesPulseRouteImport } from './routes/case-studies.pulse'
import { Route as CaseStudiesLoginDetailRouteImport } from './routes/case-studies.login-detail'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'

const NotesUXLawsRoute = NotesUXLawsRouteImport.update({
  id: '/notes/21-ux-laws',
  path: '/notes/21-ux-laws',
  getParentRoute: () => rootRoute,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperimentsRoute,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const ExperimentsRightProblemRoute = ExperimentsRightProblemRouteImport.update({
  id: '/right-problem',
  path: '/right-problem',
  getParentRoute: () => ExperimentsRoute,
} as any)
const ExperimentsMagazineWebsitesRoute =
  ExperimentsMagazineWebsitesRouteImport.update({
    id: '/magazine-websites',
    path: '/magazine-websites',
    getParentRoute: () => ExperimentsRoute,
  } as any)
const ExperimentsBokksuIndiaRoute = ExperimentsBokksuIndiaRouteImport.update({
  id: '/bokksu-india',
  path: '/bokksu-india',
  getParentRoute: () => ExperimentsRoute,
} as any)
const CaseStudiesReclaimRoute = CaseStudiesReclaimRouteImport.update({
  id: '/reclaim',
  path: '/reclaim',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesPulseRoute = CaseStudiesPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesLoginDetailRoute = CaseStudiesLoginDetailRouteImport.update({
  id: '/login-detail',
  path: '/login-detail',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/notes': typeof NotesRoute
  '/notes/21-ux-laws': typeof NotesUXLawsRoute
  '/notes/21-ux-laws': typeof NotesUXLawsRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/login-detail': typeof CaseStudiesLoginDetailRoute
  '/case-studies/pulse': typeof CaseStudiesPulseRoute
  '/case-studies/reclaim': typeof CaseStudiesReclaimRoute
  '/experiments/bokksu-india': typeof ExperimentsBokksuIndiaRoute
  '/experiments/magazine-websites': typeof ExperimentsMagazineWebsitesRoute
  '/experiments/right-problem': typeof ExperimentsRightProblemRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/experiments/': typeof ExperimentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/notes': typeof NotesRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/login-detail': typeof CaseStudiesLoginDetailRoute
  '/case-studies/pulse': typeof CaseStudiesPulseRoute
  '/case-studies/reclaim': typeof CaseStudiesReclaimRoute
  '/experiments/bokksu-india': typeof ExperimentsBokksuIndiaRoute
  '/experiments/magazine-websites': typeof ExperimentsMagazineWebsitesRoute
  '/experiments/right-problem': typeof ExperimentsRightProblemRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/experiments': typeof ExperimentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/notes': typeof NotesRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/case-studies/login-detail': typeof CaseStudiesLoginDetailRoute
  '/case-studies/pulse': typeof CaseStudiesPulseRoute
  '/case-studies/reclaim': typeof CaseStudiesReclaimRoute
  '/experiments/bokksu-india': typeof ExperimentsBokksuIndiaRoute
  '/experiments/magazine-websites': typeof ExperimentsMagazineWebsitesRoute
  '/experiments/right-problem': typeof ExperimentsRightProblemRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/experiments/': typeof ExperimentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/experiments'
    | '/notes'
    | '/notes/21-ux-laws'
    | '/case-studies/$slug'
    | '/case-studies/login-detail'
    | '/case-studies/pulse'
    | '/case-studies/reclaim'
    | '/experiments/bokksu-india'
    | '/experiments/magazine-websites'
    | '/experiments/right-problem'
    | '/case-studies/'
    | '/experiments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/notes'
    | '/notes/21-ux-laws'
    | '/case-studies/$slug'
    | '/case-studies/login-detail'
    | '/case-studies/pulse'
    | '/case-studies/reclaim'
    | '/experiments/bokksu-india'
    | '/experiments/magazine-websites'
    | '/experiments/right-problem'
    | '/case-studies'
    | '/experiments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/experiments'
    | '/notes'
    | '/case-studies/$slug'
    | '/case-studies/login-detail'
    | '/case-studies/pulse'
    | '/case-studies/reclaim'
    | '/experiments/bokksu-india'
    | '/experiments/magazine-websites'
    | '/experiments/right-problem'
    | '/case-studies/'
    | '/experiments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ExperimentsRoute: typeof ExperimentsRouteWithChildren
  NotesRoute: typeof NotesRoute
  NotesUXLawsRoute: typeof NotesUXLawsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notes/21-ux-laws': {
      id: '/notes/21-ux-laws'
      path: '/notes/21-ux-laws'
      fullPath: '/notes/21-ux-laws'
      preLoaderRoute: typeof NotesUXLawsRouteImport
      parentRoute: typeof rootRoute
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/experiments/right-problem': {
      id: '/experiments/right-problem'
      path: '/right-problem'
      fullPath: '/experiments/right-problem'
      preLoaderRoute: typeof ExperimentsRightProblemRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/experiments/magazine-websites': {
      id: '/experiments/magazine-websites'
      path: '/magazine-websites'
      fullPath: '/experiments/magazine-websites'
      preLoaderRoute: typeof ExperimentsMagazineWebsitesRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/experiments/bokksu-india': {
      id: '/experiments/bokksu-india'
      path: '/bokksu-india'
      fullPath: '/experiments/bokksu-india'
      preLoaderRoute: typeof ExperimentsBokksuIndiaRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/case-studies/reclaim': {
      id: '/case-studies/reclaim'
      path: '/reclaim'
      fullPath: '/case-studies/reclaim'
      preLoaderRoute: typeof CaseStudiesReclaimRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/pulse': {
      id: '/case-studies/pulse'
      path: '/pulse'
      fullPath: '/case-studies/pulse'
      preLoaderRoute: typeof CaseStudiesPulseRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/login-detail': {
      id: '/case-studies/login-detail'
      path: '/login-detail'
      fullPath: '/case-studies/login-detail'
      preLoaderRoute: typeof CaseStudiesLoginDetailRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesLoginDetailRoute: typeof CaseStudiesLoginDetailRoute
  CaseStudiesPulseRoute: typeof CaseStudiesPulseRoute
  CaseStudiesReclaimRoute: typeof CaseStudiesReclaimRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesLoginDetailRoute: CaseStudiesLoginDetailRoute,
  CaseStudiesPulseRoute: CaseStudiesPulseRoute,
  CaseStudiesReclaimRoute: CaseStudiesReclaimRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface ExperimentsRouteChildren {
  ExperimentsBokksuIndiaRoute: typeof ExperimentsBokksuIndiaRoute
  ExperimentsMagazineWebsitesRoute: typeof ExperimentsMagazineWebsitesRoute
  ExperimentsRightProblemRoute: typeof ExperimentsRightProblemRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

const ExperimentsRouteChildren: ExperimentsRouteChildren = {
  ExperimentsBokksuIndiaRoute: ExperimentsBokksuIndiaRoute,
  ExperimentsMagazineWebsitesRoute: ExperimentsMagazineWebsitesRoute,
  ExperimentsRightProblemRoute: ExperimentsRightProblemRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}

const ExperimentsRouteWithChildren = ExperimentsRoute._addFileChildren(
  ExperimentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ExperimentsRoute: ExperimentsRouteWithChildren,
  NotesRoute: NotesRoute,
  NotesUXLawsRoute: NotesUXLawsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
