/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperimentsIndexRouteImport } from './routes/experiments.index'
import { Route as ExperimentsRightProblemRouteImport } from './routes/experiments.right-problem'
import { Route as ExperimentsMagazineWebsitesRouteImport } from './routes/experiments.magazine-websites'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'

const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsIndexRoute = ExperimentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExperimentsRoute,
} as any)
const ExperimentsRightProblemRoute = ExperimentsRightProblemRouteImport.update({
  id: '/right-problem',
  path: '/right-problem',
  getParentRoute: () => ExperimentsRoute,
} as any)
const ExperimentsMagazineWebsitesRoute =
  ExperimentsMagazineWebsitesRouteImport.update({
    id: '/magazine-websites',
    path: '/magazine-websites',
    getParentRoute: () => ExperimentsRoute,
  } as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/notes': typeof NotesRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/experiments/magazine-websites': typeof ExperimentsMagazineWebsitesRoute
  '/experiments/right-problem': typeof ExperimentsRightProblemRoute
  '/experiments/': typeof ExperimentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/notes': typeof NotesRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/experiments/magazine-websites': typeof ExperimentsMagazineWebsitesRoute
  '/experiments/right-problem': typeof ExperimentsRightProblemRoute
  '/experiments': typeof ExperimentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/experiments': typeof ExperimentsRouteWithChildren
  '/notes': typeof NotesRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/experiments/magazine-websites': typeof ExperimentsMagazineWebsitesRoute
  '/experiments/right-problem': typeof ExperimentsRightProblemRoute
  '/experiments/': typeof ExperimentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/experiments'
    | '/notes'
    | '/case-studies/$slug'
    | '/experiments/magazine-websites'
    | '/experiments/right-problem'
    | '/experiments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/notes'
    | '/case-studies/$slug'
    | '/experiments/magazine-websites'
    | '/experiments/right-problem'
    | '/experiments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/experiments'
    | '/notes'
    | '/case-studies/$slug'
    | '/experiments/magazine-websites'
    | '/experiments/right-problem'
    | '/experiments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ExperimentsRoute: typeof ExperimentsRouteWithChildren
  NotesRoute: typeof NotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments/': {
      id: '/experiments/'
      path: '/'
      fullPath: '/experiments/'
      preLoaderRoute: typeof ExperimentsIndexRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/experiments/right-problem': {
      id: '/experiments/right-problem'
      path: '/right-problem'
      fullPath: '/experiments/right-problem'
      preLoaderRoute: typeof ExperimentsRightProblemRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/experiments/magazine-websites': {
      id: '/experiments/magazine-websites'
      path: '/magazine-websites'
      fullPath: '/experiments/magazine-websites'
      preLoaderRoute: typeof ExperimentsMagazineWebsitesRouteImport
      parentRoute: typeof ExperimentsRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
  }
}

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface ExperimentsRouteChildren {
  ExperimentsMagazineWebsitesRoute: typeof ExperimentsMagazineWebsitesRoute
  ExperimentsRightProblemRoute: typeof ExperimentsRightProblemRoute
  ExperimentsIndexRoute: typeof ExperimentsIndexRoute
}

const ExperimentsRouteChildren: ExperimentsRouteChildren = {
  ExperimentsMagazineWebsitesRoute: ExperimentsMagazineWebsitesRoute,
  ExperimentsRightProblemRoute: ExperimentsRightProblemRoute,
  ExperimentsIndexRoute: ExperimentsIndexRoute,
}

const ExperimentsRouteWithChildren = ExperimentsRoute._addFileChildren(
  ExperimentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ExperimentsRoute: ExperimentsRouteWithChildren,
  NotesRoute: NotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
